spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  
    password: PHW#84#jeor
    url: jdbc:mysql://localhost:3306/sbms39
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

        




