spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: PHW#84#jeor
    url: jdbc:mysql://localhost:3306/sbms39

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

 

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9091

